
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/cep21/xdgbasedir"

[[constraint]]
  name = "github.com/eapache/channels"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.6.0"

[[constraint]]
  name = "github.com/go-stack/stack"
  version = "1.7.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.2.4"

[[constraint]]
  name = "github.com/jawher/mow.cli"
  version = "1.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/monax/keys"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/simpleuuid"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/tendermint/abci"
  version = "0.7.1"

[[constraint]]
  branch = "master"
  name = "github.com/tendermint/ed25519"

[[constraint]]
  name = "github.com/tendermint/go-crypto"
  version = "0.4.1"

[[constraint]]
  name = "github.com/tendermint/go-wire"
  version = "0.7.1"

[[constraint]]
  name = "github.com/tendermint/merkleeyes"
  version = "0.2.4"

[[constraint]]
  name = "github.com/tendermint/tendermint"
  version = "0.12.0"

[[constraint]]
  name = "github.com/tendermint/tmlibs"
  version = "0.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/tmthrgd/go-hex"

[[constraint]]
  branch = "master"
  name = "github.com/tommy351/gin-cors"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/fatih/set.v0"
  version = "0.1.0"

[[constraint]]
  name = "gopkg.in/tylerb/graceful.v1"
  version = "1.2.15"
